
name: Skript

description: Modify how Minecraft behaves without having to write a single line of code

author: Njol
website: http://njol.ch/projects/skript

main: ch.njol.skript.Skript

#load: startup # not needed for addons, as they should add [soft-]depend: Skript to their plugin.yml
# must be uncommented to ever be able to have 'on world load' triggers

version: 1.2.1
#commands:
#    skript:
#        description: allows to modify the configuration files
#        aliases: [sk, s]
#        permission: skript.config
#        usage: /skript help

soft-depend: [Vault]

permissions:
    skript.*:
        default: false
        children:
            skript.commands: true
            #skript.config: true
    skript.commands:
        default: false
        description: allows to use effects as commands, e.g. /set health to 20
#    skript.config:
#        description: allows to modify the configuration files via commands
#        default: false
